export const ROLES = {
  GUEST: "GUEST",
  USER: "USER",
  ORGANISER: "ORGANISER",
  ADMIN: "ADMIN"
};

export const HOLD_DURATION_MINUTES = 10;
export const PASSWORD_RESET_EXPIRATION_MINUTES = 30;

export const ORDER_LIMITS = {
  MIN_TICKETS: 1,
  MAX_TICKETS: 10
};

export const CACHE_TTL = {
  AVAILABILITY_SECONDS: 5,
  CATALOG_SECONDS: 15,
  STATIC_PAGES_SECONDS: 30
};
