import { env } from "./env.js";

export const ROLES = {
  GUEST: "GUEST",
  USER: "USER",
  ORGANISER: "ORGANISER",
  ADMIN: "ADMIN"
};

export const HOLD_DURATION_MINUTES = env.HOLD_DURATION_MINUTES;
export const PASSWORD_RESET_EXPIRATION_MINUTES = env.PASSWORD_RESET_EXPIRATION_MINUTES;

export const ORDER_LIMITS = {
  MIN_TICKETS: env.ORDER_MIN_TICKETS,
  MAX_TICKETS: env.ORDER_MAX_TICKETS
};

export const CACHE_TTL = {
  AVAILABILITY_SECONDS: env.CACHE_AVAILABILITY_SECONDS,
  CATALOG_SECONDS: env.CACHE_CATALOG_SECONDS,
  STATIC_PAGES_SECONDS: env.CACHE_STATIC_PAGES_SECONDS
};

export const MAX_FILE_SIZE_BYTES = env.MAX_FILE_SIZE_MB * 1024 * 1024;

export const STORAGE_BUCKETS = {
  IMAGES: "event-images",
  TICKETS: "tickets"
};
